print("Vou te ajudar a calcular suas médias mas antes preciso de algumas informações.")
print()
nota1 = int(input("Qual foi a sua primeira nota? "))
nota2 = int(input("Qual foi a sua segunda nota? "))
nota3 = int(input("Qual foi a sua terceira nota? "))
nota4 = int(input("Qual foi a sua quarta e última nota? " ))
print()
media = (nota1 + nota2 + nota3 + nota4) / 4
print("Sua média foi:", media)
print()
print("Fim :D")